# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build_and_deploy"
  build_and_deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'

      # Build and run backend
      - name: Build and run backend
        run: |
          cd backend
          go run main.go &
          sleep 5 # Give some time for the server to start

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      # Install dependencies and build frontend
      - name: Install dependencies and build frontend
        run: |
          cd ../frontend
          npm install
          npm run build &

      # Wait for frontend build to finish
      - name: Wait for frontend build to finish
        run: sleep 120

      # Display a message with instructions on how to access the hosted website
      - name: Access website
        run: |
          echo "Backend hosted at http://localhost:8080"
          echo "Frontend hosted at http://localhost:3000"
